spring:
  application:
    name: gateway-starter-sp
  jmx:
    enabled: false
  #  cloud:
  #    gateway:
  #      default-filters:
  #        - PrefixPath=/httpbin
  #        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
  #
  #      routes:
  #        # =====================================
  #        # to run server
  #        # $ wscat --listen 9000
  #        # to run client
  #        # $ wscat --connect ws://localhost:8080/echo
  #        - id: websocket_test
  #          uri: ws://localhost:9000
  #          order: 9000
  #          predicates:
  #            - Path=/echo
  #        # =====================================
  #        - id: default_path_to_httpbin
  #          uri: ${test.uri}
  #          order: 10000
  #          predicates:
  #            - Path=/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/db_gateway?characterEncoding=utf-8
    username: root
    password: root


logging:
  path: ./log
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'gateway'

mybatis:
  type-aliases-package: org.metalohe.archi.gateway.stater.dao.model
  mapper-locations: classpath:mapper/*Mapper.xml

cus:
  router:
    uri: "http://127.0.0.1:8001/"
server:
  port: 8001